# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: joint_state.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'joint_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import header_pb2 as header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11joint_state.proto\x12\x16\x61imrt.protocols.sensor\x1a\x0cheader.proto\"N\n\nJointState\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08position\x18\x02 \x01(\x01\x12\x10\n\x08velocity\x18\x03 \x01(\x01\x12\x0e\n\x06\x65\x66\x66ort\x18\x04 \x01(\x01\"u\n\x0fJointStateArray\x12.\n\x06header\x18\x01 \x01(\x0b\x32\x1e.aimrt.protocols.common.Header\x12\x32\n\x06joints\x18\x02 \x03(\x0b\x32\".aimrt.protocols.sensor.JointStateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'joint_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOINTSTATE']._serialized_start=59
  _globals['_JOINTSTATE']._serialized_end=137
  _globals['_JOINTSTATEARRAY']._serialized_start=139
  _globals['_JOINTSTATEARRAY']._serialized_end=256
# @@protoc_insertion_point(module_scope)
