# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pose.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'pose.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import header_pb2 as header__pb2
from . import quaternion_pb2 as quaternion__pb2
from . import vector3_pb2 as vector3__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npose.proto\x12\x11genisys.protocols\x1a\x0cheader.proto\x1a\x10quaternion.proto\x1a\rvector3.proto\"v\n\x04Pose\x12\x39\n\x0borientation\x18\x01 \x01(\x0b\x32$.aimrt.protocols.geometry.Quaternion\x12\x33\n\x08position\x18\x02 \x01(\x0b\x32!.aimrt.protocols.geometry.Vector3\"d\n\x0bPoseStamped\x12.\n\x06header\x18\x01 \x01(\x0b\x32\x1e.aimrt.protocols.common.Header\x12%\n\x04pose\x18\x02 \x01(\x0b\x32\x17.genisys.protocols.Poseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pose_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSE']._serialized_start=80
  _globals['_POSE']._serialized_end=198
  _globals['_POSESTAMPED']._serialized_start=200
  _globals['_POSESTAMPED']._serialized_end=300
# @@protoc_insertion_point(module_scope)
